# Julia Basics
> adapted from https://github.com/mitmath/julia-mit,
> https://algorithmsbook.com/validation/files/val.pdf#page=397

## Julia as a calculator

In [5]:
3 + 4

7

In [6]:
3 * 4

12

In [7]:
3^4

81

In [8]:
sin(3)

0.1411200080598672

In [9]:
1 / (1 + sin(pi/4))

0.585786437626905

## Variables

In programming languages, a `variable` is a named storage location that holds a value or data.

The variable name appears on the left side of the equal sign; the value that variable
is to be assigned is on the right side.

Variable names can be any string of characters, including Unicode, with a few restrictions.

In [10]:
x = 17

17

In [11]:
y = sin(x)

-0.9613974918795568

In [12]:
α = 3.74 # Unicode variable name — type it by "\alpha<tab>"

3.74

In [13]:
β₂ = sqrt(2) # Unicode variable name — type it by "\beta<tab>\_2<tab>"

1.4142135623730951

#### Complex number:

In [14]:
z = 3 + 5im

3 + 5im

In [15]:
z^3

-198 + 10im

In [16]:
exp(z)

5.697507299833739 - 19.26050892528742im

In [17]:
sin(z)

10.472508533940392 - 73.46062169567367im

#### Online help:

In [18]:
?sin

search: sin asin sinh sinc sign sind min in asinh sinpi asind stdin isinf using



```
sin(x)
```

Compute sine of `x`, where `x` is in radians.

See also [`sind`](@ref), [`sinpi`](@ref), [`sincos`](@ref), [`cis`](@ref), [`asin`](@ref).

# Examples

```jldoctest
julia> round.(sin.(range(0, 2pi, length=9)'), digits=3)
1×9 Matrix{Float64}:
 0.0  0.707  1.0  0.707  0.0  -0.707  -1.0  -0.707  -0.0

julia> sind(45)
0.7071067811865476

julia> sinpi(1/4)
0.7071067811865475

julia> round.(sincos(pi/6), digits=3)
(0.5, 0.866)

julia> round(cis(pi/6), digits=3)
0.866 + 0.5im

julia> round(exp(im*pi/6), digits=3)
0.866 + 0.5im
```

---

```
sin(A::AbstractMatrix)
```

Compute the matrix sine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the sine. Otherwise, the sine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> sin(fill(1.0, (2,2)))
2×2 Matrix{Float64}:
 0.454649  0.454649
 0.454649  0.454649
```


In [19]:
?β₂

"β₂" can be typed by \beta<tab>\_2<tab>

search: β₂



No documentation found for private symbol.

`β₂` is of type `Float64`.

# Summary

```
primitive type Float64
```

# Supertype Hierarchy

```
Float64 <: AbstractFloat <: Real <: Number <: Any
```


## Vectors

A vector is a one-dimensional array that stores a sequence of values. We can
construct a vector using **square brackets**, separating elements by commas or spaces:

In [20]:
x = [1, 17, 32, 15]  # column vector; elements separated by commas

4-element Vector{Int64}:
  1
 17
 32
 15

In [21]:
[0 1 2] # row "vector"; elements separated by spaces

1×3 Matrix{Int64}:
 0  1  2

In [22]:
y = [15, 2, 6, -9]

4-element Vector{Int64}:
 15
  2
  6
 -9

In [23]:
x + y

4-element Vector{Int64}:
 16
 19
 38
  6

In [24]:
x * y # not allowed: vector * vector is not a linear-algebra operation

LoadError: MethodError: no method matching *(::Vector{Int64}, ::Vector{Int64})
The function `*` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:596
  *(::Dates.Period, ::AbstractArray)
   @ Dates ~/.julia/juliaup/julia-1.11.6+0.x64.linux.gnu/share/julia/stdlib/v1.11/Dates/src/periods.jl:93
  *(::LinearAlgebra.UniformScaling, ::AbstractVecOrMat)
   @ LinearAlgebra ~/.julia/juliaup/julia-1.11.6+0.x64.linux.gnu/share/julia/stdlib/v1.11/LinearAlgebra/src/uniformscaling.jl:262
  ...


In [25]:
x' # or transpose(x)

1×4 adjoint(::Vector{Int64}) with eltype Int64:
 1  17  32  15

In [26]:
x' * y # allowed = a dot product

106

In [27]:
x .* y # elementwise product

4-element Vector{Int64}:
   15
   34
  192
 -135

In [28]:
float(y)

4-element Vector{Float64}:
 15.0
  2.0
  6.0
 -9.0

In [29]:
float(y) .^ x 

4-element Vector{Float64}:
     15.0
 131072.0
      7.958661109946401e24
     -2.05891132094649e14

In [30]:
z = [3.7, 4.2, 6.1]

3-element Vector{Float64}:
 3.7
 4.2
 6.1

In [31]:
z .^ [0,1,2]

3-element Vector{Float64}:
  1.0
  4.2
 37.209999999999994

In [32]:
z .^ transpose([0,1,2]) # a Vandermonde matrix

3×3 Matrix{Float64}:
 1.0  3.7  13.69
 1.0  4.2  17.64
 1.0  6.1  37.21

In [33]:
z .^ [0 1 2]

3×3 Matrix{Float64}:
 1.0  3.7  13.69
 1.0  4.2  17.64
 1.0  6.1  37.21

In [34]:
@show x
x[2] # second element

x = [1, 17, 32, 15]


17

In [35]:
x[2:3] # elements 2 to 3 — "slicing"

2-element Vector{Int64}:
 17
 32

In [36]:
x[2:4] # elements 2,3,4

3-element Vector{Int64}:
 17
 32
 15

In [37]:
2:4

2:4

In [38]:
typeof(2:4)

UnitRange{Int64}

In [39]:
collect(0:4)

5-element Vector{Int64}:
 0
 1
 2
 3
 4

In [40]:
y .^ 3 # elementwise cube

4-element Vector{Int64}:
 3375
    8
  216
 -729

In [41]:
sin.(y) # elementwise sin

4-element Vector{Float64}:
  0.6502878401571168
  0.9092974268256817
 -0.27941549819892586
 -0.4121184852417566

In [42]:
rand(7) # 7 random numbers in [0,1)

7-element Vector{Float64}:
 0.4603433641972776
 0.8176889006221921
 0.7390005293657795
 0.7999776140181759
 0.5521535044699774
 0.747002319845256
 0.9996100275769422

In [43]:
randn(7) # 7 normally-distributed random numbers (mean 0, std. dev. 1)

7-element Vector{Float64}:
  1.188161958969538
 -1.3782987284930337
  0.9204453079102903
  0.23744212442277382
 -0.7580316157414816
 -1.3111084924264083
 -0.04831887620143691

In [44]:
collect(0:2:7) # 0 to 7 in steps of 2

4-element Vector{Int64}:
 0
 2
 4
 6

In [45]:
collect(0:0.1:7) # 0 to 7 in steps of 0.1

71-element Vector{Float64}:
 0.0
 0.1
 0.2
 0.3
 0.4
 0.5
 0.6
 0.7
 0.8
 0.9
 1.0
 1.1
 1.2
 ⋮
 5.9
 6.0
 6.1
 6.2
 6.3
 6.4
 6.5
 6.6
 6.7
 6.8
 6.9
 7.0

In [46]:
r = range(0, 2π, 50) # 50 numbers from 0 to 2π, equally spaced

0.0:0.1282282715750936:6.283185307179586

In [47]:
collect(r)

50-element Vector{Float64}:
 0.0
 0.1282282715750936
 0.2564565431501872
 0.38468481472528077
 0.5129130863003744
 0.641141357875468
 0.7693696294505615
 0.8975979010256552
 1.0258261726007487
 1.1540544441758425
 1.282282715750936
 1.4105109873260295
 1.538739258901123
 ⋮
 4.872674319853557
 5.00090259142865
 5.129130863003744
 5.257359134578837
 5.385587406153931
 5.513815677729025
 5.642043949304118
 5.770272220879212
 5.898500492454305
 6.026728764029399
 6.154957035604492
 6.283185307179586

In [48]:
r = range(0, 2π, 10^8) # not computed explicitly

0.0:6.28318537001144e-8:6.283185307179586

In [49]:
collect(r[1:10])

10-element Vector{Float64}:
 0.0
 6.28318537001144e-8
 1.256637074002288e-7
 1.884955611003432e-7
 2.513274148004576e-7
 3.14159268500572e-7
 3.769911222006864e-7
 4.398229759008008e-7
 5.026548296009151e-7
 5.654866833010296e-7

In [50]:
x = [] # empty vector

Any[]

In [51]:
x = trues(3) # Boolean vector containing three trues

3-element BitVector:
 1
 1
 1

In [52]:
x = ones(3) # vector of three ones

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [53]:
x = zeros(3) # vector of three zeros

3-element Vector{Float64}:
 0.0
 0.0
 0.0

## Matrices

In [54]:
A = [1 3 7
     4 7 2
     0 1 1]

3×3 Matrix{Int64}:
 1  3  7
 4  7  2
 0  1  1

In [55]:
B = [1 3 7; 4 7 2; 0 1 1]

3×3 Matrix{Int64}:
 1  3  7
 4  7  2
 0  1  1

In [56]:
A == B

true

In [57]:
b = [3, 2, 1] # a vector

3-element Vector{Int64}:
 3
 2
 1

In [58]:
A * b # matrix-vector product

3-element Vector{Int64}:
 16
 28
  3

In [59]:
inv(A)

3×3 Matrix{Float64}:
  0.238095   0.190476  -2.04762
 -0.190476   0.047619   1.2381
  0.190476  -0.047619  -0.238095

Let's solve a linear system $Ax = b$ for $x$:

In [60]:
x = inv(A) * b  # Never!

3-element Vector{Float64}:
 -0.9523809523809521
  0.761904761904762
  0.23809523809523808

In [61]:
A * x

3-element Vector{Float64}:
 3.0000000000000004
 2.0000000000000018
 1.0

In [62]:
A * x - b # not zero due to roundoff errors

3-element Vector{Float64}:
 4.440892098500626e-16
 1.7763568394002505e-15
 0.0

Much better:

In [63]:
x = A \ b # effectively equivalent to inv(A) * b, but faster and better

3-element Vector{Float64}:
 -0.9523809523809528
  0.7619047619047621
  0.23809523809523808

In [64]:
A * x - b # slightly different (smaller in this case)

3-element Vector{Float64}:
 0.0
 0.0
 2.220446049250313e-16

In [65]:
sin.(A) # elementwise sine

3×3 Matrix{Float64}:
  0.841471  0.14112   0.656987
 -0.756802  0.656987  0.909297
  0.0       0.841471  0.841471

In [66]:
sin(A) # what does it mean?

3×3 Matrix{Float64}:
 -0.888487  -0.296349   6.91956
  0.962251   0.264022  -3.59102
 -0.581735   0.240563   0.565852

## Functions

### Named functions

One way to define a named function is to use the `function` keyword, followed by
the name of the function and a tuple of names of arguments:

In [67]:
function f(x)
    return 3x^3 - 5x^2 + sin(x) - x
end

f (generic function with 1 method)

In [68]:
f(3)

33.141120008059865

In [69]:
f(A)

3×3 Matrix{Float64}:
 344.112    669.704  418.92
 688.962   1421.26   956.409
  87.4183   172.241  125.566

In [70]:
f.(A) # applied elementwise

3×3 Matrix{Float64}:
  -2.15853   33.1411   777.657
 107.243    777.657      2.9093
   0.0       -2.15853   -2.15853

In [71]:
f.(x) # applied elementwise

3-element Vector{Float64}:
 -6.989077393122971
 -1.6472437070737587
 -0.24519753391390525

We can also define functions compactly using assignment form:

In [72]:
g(x) = 4x^3 - 5x^2 + 6x + 2

g (generic function with 1 method)

In [73]:
g.(A)

3×3 Matrix{Int64}:
   7    83  1171
 202  1171    26
   2     7     7

### Anonymous functions

An anonymous function is not given a name, though it can be assigned to a named
variable. One way to define an anonymous function is to use the arrow operator:

In [74]:
h = x -> x^2 + 1 # assign anonymous function with input x to a variable h

#1 (generic function with 1 method)

In [75]:
h(3)

10

In [76]:
g(f, a, b) = [f(a), f(b)]; # applies function f to a and b and returns array

In [77]:
g(h, 5, 10)

2-element Vector{Int64}:
  26
 101

In [78]:
g(x->sin(x)+1, 10, 20)

2-element Vector{Float64}:
 0.4559788891106302
 1.9129452507276277

### Optional arguments

We can assign a default value to an argument, making the specification of that
argument optional:

In [79]:
f(x=10) = x^2;

In [80]:
f()

100

In [81]:
f(3)

9

In [82]:
f(x, y, z=1) = x*y + z;

In [83]:
f(1, 2, 3)

5

In [84]:
f(1, 2)

3

### Keyword arguments

Functions may use keyword arguments, which are arguments that are named
when the function is called. Keyword arguments are given after all the *positional
arguments*. A semicolon is placed before keywords, separating them from
the other arguments:

In [85]:
f(; x = 0) = x + 1;

In [86]:
f()

1

In [87]:
f(x = 10)

11

In [88]:
f(x, y = 10; z = 2) = (x + y) * z;

In [89]:
f(1)

22

In [90]:
f(2, z = 3)

36

In [91]:
f(2, 3)

10

In [92]:
f(2, 3, z = 1)

5

### Splatting

It is often useful to splat the elements of a vector or a tuple into the arguments to
a function using the ... operator:

In [1]:
f(x,y,z) = x + y - z;

In [2]:
a = [3, 1, 2];
f(a...)

2

In [3]:
b = (2, 2, 0);
f(b...)

4

In [4]:
c = ([1,2], [3,4], [5,6]);
f(c...)

2-element Vector{Int64}:
 -1
  0

### Dispatch

The types of the arguments passed to a function can be specified using the double
colon operator. If multiple methods of the same function are provided, Julia will
execute the appropriate method. The mechanism for choosing which method to
execute is called *dispatch*.        

In [5]:
f(x::Int64) = x + 10;
f(x::Float64) = x + 3.1415;

In [6]:
f(1)

11

In [7]:
f(1.0)

4.141500000000001

The method with a type signature that best matches the types of the arguments
given will be used:

In [8]:
f(x) = 5;
f(x::Float64) = 3.1415;

In [9]:
f([3, 2, 1])

5

In [10]:
f(0.00787499699)

3.1415

## Control Flow

We can control the flow of our programs using *conditional evaluation* and *loops*.

### Conditional Evaluation

Conditional evaluation will check the value of a Boolean expression and then
evaluate the appropriate block of code. One of the most common ways to do this
is with an `if statement`:

In [11]:
x = 2
y = 1

1

In [12]:
if x < y
    2*y   # run this if x < y
elseif x == y
    x + y # run this if x == y
else
    2*x   # run this if x > y
end

4

We can also use the *ternary operator* with its question mark and colon syntax.
It checks the Boolean expression before the question mark. If the expression
evaluates to true, then it returns what comes before the colon; otherwise, it
returns what comes after the colon:

In [13]:
g(x) = x > 0 ? x : 0

g (generic function with 1 method)

In [14]:
g(-10)

0

In [15]:
g(10)

10

### Loops

A loop allows for repeated evaluation of expressions. One type of loop is the
while loop, which repeatedly evaluates a block of expressions until the specified
condition after the while keyword is met. The following example sums the values
in the array X:

In [16]:
X = [1, 2, 3, 4, 6, 8, 11, 13, 16, 18]
s = 0
while !isempty(X)
    s += pop!(X)
end

@show s;
@show X;

s = 82
X = Int64[]


Another type of loop is the *for* loop, which uses the `for` keyword. The following
example will also sum over the values in the array X but will not modify X:

In [17]:
X = [1, 2, 3, 4, 6, 8, 11, 13, 16, 18]
s = 0
for y in X
    s += y
end

@show s;
@show X;

s = 82
X = [1, 2, 3, 4, 6, 8, 11, 13, 16, 18]


The `in` keyword can be replaced by `=` or `∈`.

## More Linear Algebra

Most linear-algebra routines are in the `LinearAlgebra` standard library:

In [18]:
using LinearAlgebra 

In [19]:
eigvals(A) # eigenvalues

LoadError: UndefVarError: `A` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [20]:
F = eigen(A) # eigenvectors and eigenvalues

LoadError: UndefVarError: `A` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [21]:
F.values # the eigenvalues

LoadError: UndefVarError: `F` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [ ]:
F.vectors # the eigenvectors

In [ ]:
qr(A) # QR factorization

In [ ]:
lu(A) # LU factorization

In [ ]:
svd(A)

## Plotting

You must load a plotting library. There are lots to choose from. We are using PyPlot:

In [ ]:
using PyPlot

In [ ]:
x = rand(5)
plot(x, "bo-")
grid(true)

In [ ]:
x = range(0, 2π, 1000)
y = sin.(3x + 4cos.(2x))
plot(x / 2π, y, label=L"y")
plot(x / 2π, y.^2, label=L"y^2")
plot(x / 2π, 1 ./ sqrt.(1 .+ y.^2), label=L"\frac{1}{\sqrt{1+y^2}}")
xlabel("x / 2π")
ylabel("our funny function")
title("our second plot")
grid(true)
legend();

In [ ]:
?plot

## Markdown

Here is some *italic text*, some **bold text**, some math: 
$$\int_0^1 \frac{1}{1+x^2} \, \mathrm{d}x$$.